# Generated by Django 3.1.7 on 2021-05-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_messege'),
    ]

    operations = [
        migrations.AddField(
            model_name='messege',
            name='writer',
            field=models.CharField(default='bot', max_length=20),
        ),
    ]
