# Generated by Django 3.1.7 on 2021-05-29 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_messege_writer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messege',
            new_name='Message',
        ),
    ]
