# Generated by Django 3.1.7 on 2021-05-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_reply_usermessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='reply',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='reply',
            field=models.ManyToManyField(to='chatbot.Reply'),
        ),
    ]
