# Generated by Django 3.1.7 on 2021-05-29 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_auto_20210529_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='reply',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='reply',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chatbot.reply'),
            preserve_default=False,
        ),
    ]
